# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-09-03 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Focus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_info', models.CharField(default='', max_length=200)),
            ],
            options={
                'verbose_name': '股票',
                'db_table': 'focus',
            },
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, verbose_name='股票代码')),
                ('short', models.CharField(max_length=20, verbose_name='股票简称')),
                ('chg', models.CharField(max_length=20, verbose_name='涨跌幅')),
                ('turnover', models.CharField(max_length=255, verbose_name='换手率')),
                ('price', models.FloatField(max_length=20, verbose_name='最新价')),
                ('highs', models.FloatField(max_length=20, verbose_name='前期高点')),
                ('time', models.DateField()),
            ],
            options={
                'verbose_name': '股票',
                'db_table': 'info',
            },
        ),
    ]
